homework1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('library/', include('library.urls')),
]

library/urls.py
from django.urls import path

from . import views

app_name = 'library'
urlpatterns = [
	path('', views.index, name='index'),
	path('<int:shelf_id>/', views.show_books, name='shelf'),
	path('<int:shelf_id>/<int:book_id>/', views.book, name='book'),
	path('<int:shelf_id>/add/', views.add_book, name='add_book'),
	path('<int:shelf_id>/<int:book_id>/edit/', views.edit_book, name='edit_book'),
	path('<int:shelf_id>/<int:book_id>/delete/', views.delete_book, name='delete_book'),
]

library/models.py
from django.db import models

class Shelf(models.Model):
	name = models.CharField(max_length=200)

	def __str__(self):
		return self.name

class Book(models.Model):
	shelf = models.ForeignKey(Shelf, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	author = models.CharField(max_length=100)
	description = models.CharField(max_length=200)
	status = models.BooleanField(default=True, choices=[
		(True, 'Available'),
		(False, 'Not available'),
	])

	def __str__(self):
		return self.title

library/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Shelf, Book

def index(request):
	context = {
		'shelves' : Shelf.objects.all(),
	}
	return render(request, 'library/index.html', context)

def show_books(request, shelf_id):
	shelf = get_object_or_404(Shelf, pk=shelf_id)
	all_books = shelf.book_set.all()
	context = {
		'shelf' : shelf,
		'books' : all_books,
	}
	return render(request, 'library/shelf.html', context)

def add_book(request, shelf_id):
	book = Book(
		shelf=Shelf.objects.filter(pk=shelf_id)[0],
		title=request.POST['title'],
		author=request.POST['author'],
		description=request.POST['description'],
		status=request.POST['status'],
	)
	book.save()
	return HttpResponseRedirect(reverse('library:shelf', args=(shelf_id,)))

def edit_book(request, shelf_id, book_id):
	book = get_object_or_404(Book, pk=book_id)
	book.title = request.POST['title']
	book.author = request.POST['author']
	book.description = request.POST['description']
	book.status = request.POST['status']
	book.save()
	return HttpResponseRedirect(reverse('library:book', args=(shelf_id,book_id)))
	
def delete_book(request, shelf_id, book_id):
	book = get_object_or_404(Book, pk=book_id)
	book.delete()
	return HttpResponseRedirect(reverse('library:shelf', args=(shelf_id,)))

def book(request, shelf_id, book_id):
	book = get_object_or_404(Book, pk=book_id)
	context = {
		'book': book,
		'shelf_id': shelf_id,
	}
	return render(request, 'library/book.html', context)

def take_book(request, book_id):
	book = get_object_or_404(Book, pk=book_id)
	if(book.status):
		book.status = False
		book.save()
		context = {'book': book, 'shelf_id': shelf_id}
	else:
		context = {
			'book': book,
			'shelf_id': shelf_id,
			'answer': "Sorry this book is currently not available."
		}
	return render(request, 'library/book.html', context)

def return_book(request, book_id):
	book = get_object_or_404(Book, pk=book_id)
	if(not book.status):
		book.status = True
		book.save()
	context = {'book': book, 'shelf_id': shelf_id}
	return render(request, 'library/book.html', context)

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>Library</title>
</head>
<body>
	{% block body %}
	
	{% endblock %}
</body>
</html>

library/templates/library/book.html
{% extends "library/base.html" %}

{% block body %}
<h2>{{book.title}}</h2>
<h4>{{book.author}}</h4>
<p>{{book.description}}</p>
{% if book.status %}
	<p>Status: Available</p>    
{% else %}
	<p>Status: Not available</p>
{% endif %}
<br><br>
<form action="{% url 'library:edit_book' shelf_id=shelf_id book_id=book.id %}" method="post">
{%csrf_token%}
	<label for="title">Title: </label><br>
	<input name="title" id="title" value="{{book.title}}"><br>
	<label for="author">Author: </label><br>
	<input name="author" id="author" value="{{book.author}}"><br>
	<label for="description">Description: </label><br>
	<textarea name="description" id="description">{{book.description}}</textarea><br>
	<label for="status">Status: </label><br>
	<select id="status" name="status"><br>
		{% if book.status %}
			<option value="0">Not Available</option>
			<option value="1" selected>Available</option>
		{% else %}
			<option value="0" selected>Not Available</option>
			<option value="1">Available</option>	
		{% endif %}	
	</select>
	<input type="submit" value="Edit">
</form>

<form action="{% url 'library:delete_book' shelf_id=shelf_id book_id=book.id %}" method="post">
	{%csrf_token%}
	<input type="submit" value="Delete">
</form>

<br>
<a href="{% url 'library:shelf' shelf_id %}">Back to the shelf</a>
{% endblock %}

library/templates/library/index.html
{% extends "library/base.html" %}

{% block body %}
{% if shelves %}
<ul>
	{% for shelf in shelves %}
		<li><a href='{% url "library:shelf" shelf.id %}'>{{shelf.id}} - {{shelf.name}}</a></li>
	{% endfor %}
</ul>
{% else %}
<p>Sorry, the library is empty</p>
{% endif %}
{% endblock %}

library/templates/library/shelf.html
{% extends "library/base.html" %}

{% block body %}
<h1>{{shelf.name}}</h1>
<ul>
{% for book in books %}
	<li><a href="{% url 'library:book' shelf_id=shelf.id book_id=book.id %}">{{book.title}}</a></li>
{% endfor %}
</ul>
<br>
<form action="{% url 'library:add_book' shelf.id %}" method="post">
{%csrf_token%}
<label for="title">Title: </label><br>
<input name="title" id="title"><br>
<label for="author">Author: </label><br>
<input name="author" id="author"><br>
<label for="description">Description: </label><br>
<textarea name="description" id="description"></textarea><br>
<label for="status">Status: </label><br>
<select id="status" name="status"><br>
	<option value="0">Not Available</option>
	<option value="1" selected>Available</option>
</select>
<input type="submit" value="Add">
</form>
<br>
<br>
<a href="{% url 'library:index' %}">Back to shelves</a>
{% endblock %}